/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    3.1.0.43.2
    Soft IP Version: 1.0.0
    2022 03 05 10:54:39
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module my_osc (rst_i, ipload_i, ipdone_o, sb_clk_i, sb_wr_i, sb_stb_i,
    sb_adr_i, sb_dat_i, sb_dat_o, sb_ack_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  rst_i;
    input  ipload_i;
    output  ipdone_o;
    input  sb_clk_i;
    input  sb_wr_i;
    input  sb_stb_i;
    input  [7:0]  sb_adr_i;
    input  [7:0]  sb_dat_i;
    output  [7:0]  sb_dat_o;
    output  sb_ack_o;
endmodule