/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    3.1.1.232.1
    Soft IP Version: 1.0.0
    2022 03 25 09:21:53
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module i2c (i2c2_scl_io, i2c2_sda_io, rst_i, ipload_i, ipdone_o, sb_clk_i,
    sb_wr_i, sb_stb_i, sb_adr_i, sb_dat_i, sb_dat_o, sb_ack_o, i2c_pirq_o,
    i2c_pwkup_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    inout  i2c2_scl_io;
    inout  i2c2_sda_io;
    input  rst_i;
    input  ipload_i;
    output  ipdone_o;
    input  sb_clk_i;
    input  sb_wr_i;
    input  sb_stb_i;
    input  [7:0]  sb_adr_i;
    input  [7:0]  sb_dat_i;
    output  [7:0]  sb_dat_o;
    output  sb_ack_o;
    output  [1:0]  i2c_pirq_o;
    output  [1:0]  i2c_pwkup_o;
endmodule