/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    3.1.0.43.2
    Soft IP Version: 1.1.0
    2022 03 04 16:45:02
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module rom_himax_cfg_20fps_ir (rd_clk_i, rst_i, rd_en_i, rd_clk_en_i,
    rd_addr_i, rd_data_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  rd_clk_i;
    input  rst_i;
    input  rd_en_i;
    input  rd_clk_en_i;
    input  [7:0]  rd_addr_i;
    output  [15:0]  rd_data_o;
endmodule