    my_osc __(.rst_i( ),
        .ipload_i( ),
        .ipdone_o( ),
        .sb_clk_i( ),
        .sb_wr_i( ),
        .sb_stb_i( ),
        .sb_adr_i( ),
        .sb_dat_i( ),
        .sb_dat_o( ),
        .sb_ack_o( ));
